name: Auth Sync App Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Checkout Config
        uses: actions/checkout@v3
        with:
          repository: "bcgov-nr/auth-sync-config-${{ inputs.name }}"
          token: ${{ secrets.GH_PAT }}
          path: config

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      # Runs script to obtain CSS secrets
      - name: Role Sync
        run: ./bin/dev role-sync
        env:
          CSS_TOKEN_URL: ${{ secrets.CSS_TOKEN_URL }}
          CSS_CLIENT_ID: ${{ secrets.CSS_CLIENT_ID }}
          CSS_CLIENT_SECRET: ${{ secrets.CSS_CLIENT_SECRET }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

      - name: Member Sync
        run: ./bin/dev member-sync
        env:
          BROKER_API_URL: ${{ secrets.BROKER_API_URL }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
          CSS_TOKEN_URL: ${{ secrets.CSS_TOKEN_URL }}
          CSS_CLIENT_ID: ${{ secrets.CSS_CLIENT_ID }}
          CSS_CLIENT_SECRET: ${{ secrets.CSS_CLIENT_SECRET }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
