name: Auth Sync App Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Checkout Config
        uses: actions/checkout@v4
        with:
          repository: "bcgov-nr/auth-sync-config-${{ inputs.name }}"
          token: ${{ secrets.GH_PAT }}
          path: config

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Generate
        run: ./bin/dev generate
        env:
          BROKER_API_URL: ${{ secrets.BROKER_API_URL }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
          CSS_TOKEN_URL: ${{ secrets.CSS_TOKEN_URL }}
          CSS_CLIENT_ID: ${{ secrets.CSS_CLIENT_ID }}
          CSS_CLIENT_SECRET: ${{ secrets.CSS_CLIENT_SECRET }}
          SOURCE_BROKER_DOMAIN: 'azureidir'

      - name: Role Sync
        run: ./bin/dev role-sync
        env:
          BROKER_API_URL: ${{ secrets.BROKER_API_URL }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
          CSS_TOKEN_URL: ${{ secrets.CSS_TOKEN_URL }}
          CSS_CLIENT_ID: ${{ secrets.CSS_CLIENT_ID }}
          CSS_CLIENT_SECRET: ${{ secrets.CSS_CLIENT_SECRET }}
          SOURCE_BROKER_DOMAIN: 'azureidir'

      - name: Member Sync
        run: ./bin/dev member-sync
        env:
          BROKER_API_URL: ${{ secrets.BROKER_API_URL }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
          CSS_TOKEN_URL: ${{ secrets.CSS_TOKEN_URL }}
          CSS_CLIENT_ID: ${{ secrets.CSS_CLIENT_ID }}
          CSS_CLIENT_SECRET: ${{ secrets.CSS_CLIENT_SECRET }}
          SOURCE_BROKER_DOMAIN: 'azureidir'
